################################################################################
#   SECTION: Capabilities
################################################################################
Capabilities:
    Channel: &ChannelCapabilities
        <%=  networkSettings.capabilities.channel %>: true
    Orderer: &OrdererCapabilities
        <%=  networkSettings.capabilities.orderer %>: true
    Application: &ApplicationCapabilities
        <%=  networkSettings.capabilities.application %>: true

################################################################################
#   CHANNEL Defaults
################################################################################
Channel: &ChannelDefaults
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
    Capabilities:
        <<: *ChannelCapabilities

################################################################################
#   Section: Organizations
################################################################################
Organizations:
<%_ ordererOrgs.forEach(function(ordererOrg) { _%>
    - &<%= ordererOrg.name %>Org
        Name: <%= ordererOrg.mspName %>
        ID: <%= ordererOrg.mspName %>
        MSPDir: crypto-config/ordererOrganizations/<%= ordererOrg.domain %>/msp

        Policies:
            Readers:
                Type: Signature
                Rule: "OR('<%= ordererOrg.mspName %>.member')"
            Writers:
                Type: Signature
                Rule: "OR('<%= ordererOrg.mspName %>.member')"
            Admins:
                Type: Signature
                Rule: "OR('<%= ordererOrg.mspName %>.admin')"

<%_ }) _%>

<% orgs.forEach(function(org){ %>
    - &<%= org.name %>
      Name: <%= org.mspName %>
      ID: <%= org.mspName %>
      MSPDir: crypto-config/peerOrganizations/<%= org.domain %>/msp

      Policies:
          Readers:
              Type: Signature
              Rule: "OR('<%= org.mspName %>.member')"
          Writers:
              Type: Signature
              Rule: "OR('<%= org.mspName %>.member')"
          Admins:
              Type: Signature
              Rule: "OR('<%= org.mspName %>.admin')"
          Endorsement:
              Type: Signature
              Rule: "OR('<%= org.mspName %>.member')"

      AnchorPeers:<% org.anchorPeers.forEach(function(anchorPeer){ %>
          - Host: <%= anchorPeer.address %>
            Port: <%= anchorPeer.port %><% })}) %>

################################################################################
#   SECTION: Application
################################################################################
Application: &ApplicationDefaults
    Organizations:
    # Policies defines the set of policies at this level of the config tree
    # For Application policies, their canonical path is
    #   /Channel/Application/<PolicyName>
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
        Endorsement:
            Type: ImplicitMeta
            Rule: "MAJORITY Endorsement"
    Capabilities:
        <<: *ApplicationCapabilities

################################################################################
#   SECTION: Orderer
################################################################################
<%_ ordererOrgs.forEach(function(ordererOrg) { _%>
Orderer: &<%= ordererOrg.mspName %>Defaults
    OrdererType: <%= ordererOrg.consensus %>
    Addresses:<% ordererOrg.orderers.forEach(function(orderer) { %>
        - <%= orderer.fullAddress %><% })-%>
<%- include('configtx-raft-template.yaml.ejs', {ordererOrg: ordererOrg}); %>
    BatchTimeout: 2s
    BatchSize:
        MaxMessageCount: 10
        AbsoluteMaxBytes: 99 MB
        PreferredMaxBytes: 512 KB
    Organizations:
    # Policies defines the set of policies at this level of the config tree
    # For Orderer policies, their canonical path is
    #   /Channel/Orderer/<PolicyName>
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
        # BlockValidation specifies what signatures must be included in the block
        # from the orderer for the peer to validate it.
        BlockValidation:
            Type: ImplicitMeta
            Rule: "ANY Writers"
    Capabilities:
        <<: *OrdererCapabilities

<% }) %>
################################################################################
#   Profile
################################################################################
# https://github:com/hyperledger/fabric/blob/master/sampleconfig/configtx.yaml

Profiles:
<%_ ordererOrgs.forEach(function(ordererOrg) { _%>
    # Profile used to create Genesis block for group <%= ordererOrg.name %>#
    <%= ordererOrg.profile %>:
        <<: *ChannelDefaults
        Orderer:
            <<: *<%= ordererOrg.mspName %>Defaults
            Organizations:
                - *<%= ordererOrg.name %>Org
            Capabilities:
                <<: *OrdererCapabilities
        Consortiums:
            SampleConsortium:
                Organizations:
                <%_ orgs.forEach(function(org){ _%>
                    - *<%= org.name %>
                <%_ }) _%>

<%_ }) _%>
<% channels.forEach(function(channel) { %>
    # Profile used to create channeltx for <%= channel.name %> #
    <%= channel.profileName %>:
        <<: *ChannelDefaults
        Consortium: SampleConsortium
        Consortiums:
            SampleConsortium:
                Organizations:<% channel.orgs.forEach(function(org){ %>
                    - *<%= org.name %><% }) %>
        Application:
            <<: *ApplicationDefaults
            Organizations:<% channel.orgs.forEach(function(org){ %>
                - *<%= org.name %><% }) %>
        Orderer:
            <<: *<%= ordererOrgs[0].mspName %>Defaults
            Organizations:<% channel.orgs.forEach(function(org){ %>
                - *<%= org.name %><% }) %>
            Capabilities:
                <<: *ApplicationCapabilities
<% }) %>
