################################################################################
#   SECTION: Capabilities
################################################################################
Capabilities:
    Channel: &ChannelCapabilities
        <%=  global.capabilities.channel %>: true
    Orderer: &OrdererCapabilities
        <%=  global.capabilities.orderer %>: true
    Application: &ApplicationCapabilities
        <%=  global.capabilities.application %>: true

################################################################################
#   CHANNEL Defaults
################################################################################
Channel: &ChannelDefaults
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
    Capabilities:
        <<: *ChannelCapabilities

################################################################################
#   Section: Organizations
################################################################################
Organizations:
<%_ orgs.forEach(function(org){ _%>
    - &<%= org.name %>
      Name: <%= org.mspName %>
      ID: <%= org.mspName %>
      MSPDir: crypto-config/peerOrganizations/<%= org.domain %>/msp

      Policies:
          Readers:
              Type: Signature
              Rule: "OR('<%= org.mspName %>.member')"
          Writers:
              Type: Signature
              Rule: "OR('<%= org.mspName %>.member')"
          Admins:
              Type: Signature
              Rule: "OR('<%= org.mspName %>.admin')"
          Endorsement:
              Type: Signature
              Rule: "OR('<%= org.mspName %>.member')"

      AnchorPeers:
        <%_ org.anchorPeers.forEach(function(anchorPeer){ _%>
          - Host: <%= anchorPeer.address %>
            Port: <%= anchorPeer.port %>

        <%_ }) _%>

<%_ }) _%>

################################################################################
#   SECTION: Application
################################################################################
Application: &ApplicationDefaults
    Organizations:
    # Policies defines the set of policies at this level of the config tree
    # For Application policies, their canonical path is
    #   /Channel/Application/<PolicyName>
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
        Endorsement:
            Type: ImplicitMeta
            Rule: "MAJORITY Endorsement"
    Capabilities:
        <<: *ApplicationCapabilities

################################################################################
#   SECTION: Orderer
################################################################################
<%_ ordererGroups.forEach(function(ordererGroup) { _%>
Orderer: &<%= ordererGroup.configtxOrdererDefaults %>
    OrdererType: <%= ordererGroup.consensus %>
    Addresses:<% ordererGroup.orderers.forEach(function(orderer) { %>
        - <%= orderer.fullAddress %><% })-%>
<%- include('configtx-raft-template.yaml.ejs', {ordererGroup: ordererGroup}); %>
    BatchTimeout: 2s
    BatchSize:
        MaxMessageCount: 10
        AbsoluteMaxBytes: 99 MB
        PreferredMaxBytes: 512 KB
    Organizations:
    # Policies defines the set of policies at this level of the config tree
    # For Orderer policies, their canonical path is
    #   /Channel/Orderer/<PolicyName>
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
        # BlockValidation specifies what signatures must be included in the block
        # from the orderer for the peer to validate it.
        BlockValidation:
            Type: ImplicitMeta
            Rule: "ANY Writers"
    Capabilities:
        <<: *OrdererCapabilities

<%_ }) _%>
################################################################################
#   Profile
################################################################################
# https://github:com/hyperledger/fabric/blob/master/sampleconfig/configtx.yaml

Profiles:
<%_ ordererGroups.forEach(function(ordererGroup) { _%>
    # Profile used to create Genesis block for group <%= ordererGroup.name %> #
    <%= ordererGroup.profileName %>:
        <<: *ChannelDefaults
        Orderer:
            <<: *<%= ordererGroup.configtxOrdererDefaults %>
            Organizations:
            <%_ ordererGroup.hostingOrgs.forEach(function(hostingOrg) { _%>
                - *<%= hostingOrg %>
            <%_ }) _%>
            Capabilities:
                <<: *OrdererCapabilities
        Consortiums:
            SampleConsortium:
                Organizations:
                <%_ orgs.forEach(function(org){ _%>
                    - *<%= org.name %>
                <%_ }) _%>

<%_ }) _%>
<%_ channels.forEach(function(channel) { _%>
    # Profile used to create channeltx for <%= channel.name %> #
    <%= channel.profileName %>:
        <<: *ChannelDefaults
        Orderer:
            <<: *<%= channel.ordererGroup.configtxOrdererDefaults %>
            Organizations:
            <%_ channel.ordererGroup.hostingOrgs.forEach(function(hostingOrg) { _%>
                - *<%= hostingOrg %>
            <%_ }) _%>
            Capabilities:
                <<: *ApplicationCapabilities
        Consortium: SampleConsortium
        Consortiums:
            SampleConsortium:
                Organizations:<% channel.orgs.forEach(function(org){ %>
                    - *<%= org.name %><% }) %>
        Application:
            <<: *ApplicationDefaults
            Organizations:<% channel.orgs.forEach(function(org){ %>
                - *<%= org.name %><% }) %>

<%_ }) _%>
