<% if(!isHlf20) { %>################################################################################
#   SECTION: Capabilities
################################################################################
Capabilities:
    Channel: &ChannelCapabilities
        <%=  capabilities.channel %>: true
    Orderer: &OrdererCapabilities
        <%=  capabilities.orderer %>: true
    Application: &ApplicationCapabilities
        <%=  capabilities.application %>: true<% } %>

################################################################################
#   CHANNEL Defaults
################################################################################
Channel: &ChannelDefaults
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
    Capabilities:
        <% if(!isHlf20) { %><<: *ChannelCapabilities<% } %>

################################################################################
#   Section: Organizations
################################################################################
Organizations:
    - &OrdererOrg
      Name: <%= rootOrg.organization.name %>
      ID: <%= rootOrg.organization.mspName %>
      MSPDir: crypto-config/ordererOrganizations/<%= rootOrg.organization.domain %>/msp
<% if(isHlf20) { %>
      Policies:
          Readers:
              Type: Signature
              Rule: "OR('<%= rootOrg.organization.mspName %>.member')"
          Writers:
              Type: Signature
              Rule: "OR('<%= rootOrg.organization.mspName %>.member')"
          Admins:
              Type: Signature
              Rule: "OR('<%= rootOrg.organization.mspName %>.admin')"<%} orgs.forEach(function(org){ %>
    - &<%= org.name %>
      Name: <%= org.mspName %>
      ID: <%= org.mspName %>
      MSPDir: crypto-config/peerOrganizations/<%= org.domain %>/msp
<% if(isHlf20) { %>Policies:
          Readers:
              Type: Signature
              Rule: "OR('<%= org.mspName %>.admin', '<%= org.mspName %>.peer', '<%= org.mspName %>.client')"
          Writers:
              Type: Signature
              Rule: "OR('<%= org.mspName %>.admin', '<%= org.mspName %>.client')"
          Admins:
              Type: Signature
              Rule: "OR('<%= org.mspName %>.admin')"
          Endorsement:
              Type: Signature
              Rule: "OR('<%= org.mspName %>.peer')"<% } -%>
      AnchorPeers:<% org.anchorPeers.forEach(function(anchorPeer){ %>
          - Host: <%= anchorPeer.address %>
            Port: <%= anchorPeer.port %><% })}) %>

################################################################################
#   SECTION: Application
################################################################################
Application: &ApplicationDefaults
    Organizations:
    Capabilities:
        <% if(!isHlf20) { %><<: *ApplicationCapabilities<% } %>
<% if(isHlf20) { %># Policies defines the set of policies at this level of the config tree
    # For Application policies, their canonical path is
    #   /Channel/Application/<PolicyName>
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
        LifecycleEndorsement:
            Type: ImplicitMeta
            Rule: "MAJORITY Endorsement"
        Endorsement:
            Type: ImplicitMeta
            Rule: "MAJORITY Endorsement"<% } %>

################################################################################
#   SECTION: Orderer
################################################################################
Orderer: &OrdererDefaults
    OrdererType: <%= rootOrg.ordererHead.consensus %>
    Addresses:<% rootOrg.orderers.forEach(function(orderer) { %>
        - <%= orderer.fullAddress %><% })-%>
<%- include('configtx-raft-template.yaml.ejs', {rootOrg: rootOrg}); %>
    BatchTimeout: 2s
    BatchSize:
        MaxMessageCount: 10
        AbsoluteMaxBytes: 99 MB
        PreferredMaxBytes: 512 KB
    Organizations:<% if(isHlf20) { %>
    # Policies defines the set of policies at this level of the config tree
    # For Orderer policies, their canonical path is
    #   /Channel/Orderer/<PolicyName>
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
        # BlockValidation specifies what signatures must be included in the block
        # from the orderer for the peer to validate it.
        BlockValidation:
            Type: ImplicitMeta
            Rule: "ANY Writers"<% } %>

################################################################################
#   Profile
################################################################################
# https://github:com/hyperledger/fabric/blob/master/sampleconfig/configtx.yaml

Profiles:
    OrdererGenesis:
        <<: *ChannelDefaults
        Orderer:
            <<: *OrdererDefaults
            Organizations:
                - *OrdererOrg
            Capabilities:
                <% if(!isHlf20) { %><<: *OrdererCapabilities<% } %>
        Consortiums:
            SampleConsortium:
                Organizations:<% orgs.forEach(function(org){ %>
                    - *<%= org.name %><% }) %>
    AllOrgChannel:
        <<: *ChannelDefaults
        Consortium: SampleConsortium
        Application:
            <<: *ApplicationDefaults
            Organizations:<% orgs.forEach(function(org){ %>
                - *<%= org.name %><% }) %>
            Capabilities:
                <% if(!isHlf20) { %><<: *ApplicationCapabilities<% } %>
